### ISSUE TITLE
Is the main can run off-line?

### ISSUE THREAD

**Issue by lszhou0126** [ggerganov/wave-share#1]
I see main.c has a main function, and can I build it to run on my ubuntu computer, like https://ggerganov.github.io/wave-share can send and receive data.
Thanks!

**Comment by ggerganov** [comment]
The `main.cpp` is just used to build the wasm module - it is not meant to be used as a standalone tool. For a standalone application you can check the https://github.com/ggerganov/wave-gui project - it implements pretty much the same algorithm (up to parameter settings).

**Comment by lszhou0126** [comment]
@ggerganov why https://ggerganov.github.io/jekyll/update/2018/11/17/wave-gui.html always print: [WARNG] Not using ECC because the specified number of ECC bytes is too big for this protocol. And maybe some mistake in Receiving. Is there any suggestion for the parameter settings of wave-gui and have the same performance to wave-share.

**Comment by ggerganov** [comment]
OK, ignore my previous comment.

I modified `main.cpp` so it can be built both as wasm module and standalone tool. Check the updated README for info how to build.

Here is a short demo of me running it in the terminal: https://youtu.be/TcfjCMCyqF0
