### ISSUE TITLE
sometimes the received string is wrong

### ISSUE THREAD

**Issue by lszhou0126** [ggerganov/wave-share#2]
Hello,
Sometimes the receiver print a string, but not the same to sender, there is some mistake, especially at low volume. Is there any solution, since the wrong return may cause other problems.

**Comment by ggerganov** [comment]
Hi, you can try to modify the code to increase the number of ECC bytes - those are used for recovering errors. More bytes means more errors can be recovered, but also longer transmission time.

See the `getECCBytesForLength(int len)` function `main.cpp`.

**Comment by lszhou0126** [comment]
Hi, I have another question. What will happen if some of the ECC values went wrong. May it happened that the payload is right, but the wrong ECC value correct the payload to a wrong ouput?

**Comment by ggerganov** [comment]
The magic of the Reed-Solomon error correction is that it does not matter where the errors occurred - with `2*N` ECC bytes, one can recover up to `N` wrong bytes regardless if they are in the payload or in the ECC bytes. I won't pretend to understand the theory behind it, but I have tested it and it does work :)

So the answer to your question is - no, it cannot happen (unless of course there are more than `N` errors, but then you have to reconsider the length of the ECC bytes)
