### ISSUE TITLE
I feel like I don't understand what this is for

### ISSUE THREAD

**Issue by StoneCypher** [ggerganov/wave-share#3]
It looks like you're making a WebRTC modem so that you can get data across WebRTC

[WebRTC has a data channel](https://webrtc.org/getting-started/data-channels)

Am I misunderstanding what this is for?

**Comment by ggerganov** [comment]
The sound is not used to transfer the actual data. It is only used for the "signaling" stage in which 2 peers negotiate a WebRTC connection with each other and its properties. Basically, peer A emits a sound wave saying "I want to send this file and my WebRTC session info is this". Someone nearby (peer B), hears this sound and emits another sound saying "Ok, I want to receive this file, here is my WebRTC session info". The rest of the communication is done through WebRTC.

**Comment by StoneCypher** [comment]
So what stops you from being snooped?

**Comment by ggerganov** [comment]
Nothing - it's not meant to be secure. Rather it is meant to be convenient. Something like an audio QR code.

**Comment by bityob** [comment]
@ggerganov 

Why not sending all the data already using the sound channel?

I mean after the signaling stage, just send the data itself in this sound channel. 

This is much more like QR code where both devices are not on the same LAN 
and the data is transferred only with the QR code data.

Thanks

**Comment by ggerganov** [comment]
Of course it is possible to send the data directly through sound, without using WebRTC at all. The main issue with that is the data rate is very low.

Check my blog post on this for more info: https://ggerganov.github.io/jekyll/update/2018/05/31/data-over-sound-2.html
